# Gravatar email
gravatar_email: images/test.jpg

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "http://placehold.it/450x320"

# Default post cover index page (Optional)
default_cover_detail: "http://placehold.it/1300x500"

# Show Dates for posts and pages
show_dates: true

# Style of home page 'blog' or 'thumbs'
style: thume

# About page for call to action on home page
about_page: page

# favicon
favicon: images/resume.ico

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: livingos
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
whatsapp_url: https://api.whatsapp.com/send?1=pt_BR&phone=5543999046629
facebook_url: https://www.facebook.com/kao.y.chun
linkedin_url: https://www.linkedin.com/in/kao-yu-chun-9b35a949/
instagram_url: https://www.instagram.com/chunkaoyu/?hl=pt-br
github_url: https://github.com/KaoYuChunG
